(() => {
  'use strict';
  const SHEET_ID='1fSN5bKFz-tC3AxLItB7uYDhsjNa1qGlo3ekUDpddU-I';
  const TABS=['Configuracion','Menu','Banners','Productos','Servicios','Paginas','Testimonios','Redes_y_contacto','Cobertura'];
  const state={};
  const clean=v=>v==null?'':String(v).trim();
  const yes=v=>['sí','si','yes','true','1'].includes(clean(v).toLowerCase());
  const esc=v=>clean(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const split=v=>clean(v).split('|').map(x=>x.trim()).filter(Boolean);
  const valid=v=>v&&!/PEGAR_|EJEMPLO/i.test(v);
  const FALLBACK_COORDS=[['San Andrés y Providencia',14,11],['La Guajira',51,7],['Atlántico',41,10],['Magdalena',45,12],['Cesar',48,17],['Sucre',38,20],['Bolívar',39,22],['Córdoba',34,24],['Norte de Santander',57,25],['Antioquia',36,36],['Santander',52,30],['Arauca',67,31],['Chocó',27,37],['Boyacá',55,35],['Casanare',64,39],['Caldas',41,40],['Risaralda',38,42],['Quindío',40,44],['Cundinamarca',50,43],['Bogotá D.C.',51,44],['Tolima',45,47],['Valle del Cauca',32,49],['Meta',58,50],['Vichada',77,42],['Cauca',35,55],['Huila',45,54],['Guainía',78,50],['Guaviare',66,56],['Nariño',30,61],['Caquetá',54,63],['Putumayo',42,68],['Vaupés',71,65],['Amazonas',54,84]];
  const FALLBACK_PRODUCTS=[
    {Categoría:'Camisas y camisetas',Nombre:'Camiseta personalizada','Descripción corta':'Para marcas, eventos, colecciones y dotaciones.','Tallas (separadas por |)':'XS|S|M|L|XL|XXL|Otra','Materiales (separados por |)':'Burda|Tela fría|Algodón|Piqué|Consultar otra tela','Colores (separados por |)':'Negro|Blanco|Azul|Rojo|Verde|Otro color','Cantidad mínima':1,Personalización:'Bordado|DTF|Screen|Sublimación|Etiquetas','Mensaje WhatsApp':'Hola Genes Creativos, quiero cotizar una camiseta personalizada.',Activo:'Sí'},
    {Categoría:'Hoodies y buzos',Nombre:'Hoodie personalizado','Descripción corta':'Con o sin capota, clásico u oversized.','Tallas (separadas por |)':'XS|S|M|L|XL|XXL|Otra','Materiales (separados por |)':'Algodón perchado|Burda premium|French terry|Fleece|Consultar otra tela','Colores (separados por |)':'Negro|Blanco|Gris|Azul|Otro color','Cantidad mínima':1,Personalización:'Bordado|DTF|Screen|Etiquetas','Mensaje WhatsApp':'Hola Genes Creativos, quiero cotizar un hoodie personalizado.',Activo:'Sí'},
    {Categoría:'Jeans y pantalones',Nombre:'Jean o pantalón personalizado','Descripción corta':'Siluetas urbanas, corporativas o casuales.','Tallas (separadas por |)':'28|30|32|34|36|38|Otra','Materiales (separados por |)':'Denim rígido|Denim stretch|Dril|Antifluido|Consultar otra tela','Colores (separados por |)':'Índigo oscuro|Índigo claro|Negro|Caqui|Otro color','Cantidad mínima':1,Personalización:'Lavados|Bolsillos|Herrajes|Etiquetas','Mensaje WhatsApp':'Hola Genes Creativos, quiero cotizar un jean o pantalón.',Activo:'Sí'},
    {Categoría:'Chaquetas y gorras',Nombre:'Accesorios personalizados','Descripción corta':'Prendas y accesorios para equipos, marcas y colecciones.','Tallas (separadas por |)':'XS|S|M|L|XL|XXL|Única','Materiales (separados por |)':'Impermeable|Dril|Algodón|Poliéster|Consultar otra tela','Colores (separados por |)':'Negro|Azul|Gris|Beige|Otro color','Cantidad mínima':1,Personalización:'Bordado|DTF|Parches|Etiquetas','Mensaje WhatsApp':'Hola Genes Creativos, quiero cotizar chaquetas o gorras personalizadas.',Activo:'Sí'}
  ];

  function driveImage(value){const url=clean(value);if(!valid(url))return'';const m=url.match(/\/d\/([\w-]+)/)||url.match(/[?&]id=([\w-]+)/);return m?`https://drive.google.com/thumbnail?id=${m[1]}&sz=w1600`:url;}
  function loadTab(tab,index){return new Promise((resolve,reject)=>{const callback=`__genesLanding${index}_${Date.now()}`;const script=document.createElement('script');const timer=setTimeout(()=>{done();reject(new Error(tab));},8000);function done(){clearTimeout(timer);delete window[callback];script.remove();}window[callback]=response=>{try{if(!response||response.status!=='ok')throw new Error(tab);const rows=(response.table.rows||[]).map(r=>(r.c||[]).map(c=>c?(c.v??''):''));const hi=rows.findIndex(r=>clean(r[0]).toLowerCase()==='id');if(hi<0)throw new Error(tab);const heads=rows[hi].map(clean);const records=rows.slice(hi+1).filter(r=>clean(r[0])).map(r=>Object.fromEntries(heads.map((h,i)=>[h,r[i]??'']).filter(x=>x[0])));done();resolve(records);}catch(e){done();reject(e);}};script.onerror=()=>{done();reject(new Error(tab));};const tqx=`out:json;responseHandler:${callback}`;script.src=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?sheet=${encodeURIComponent(tab)}&headers=0&tqx=${encodeURIComponent(tqx)}&t=${Date.now()}`;document.head.appendChild(script);});}
  function config(){return Object.fromEntries((state.Configuracion||[]).filter(r=>yes(r.Activo)).map(r=>[clean(r.Campo),r.Valor]));}
  function pageText(section,field){const row=(state.Paginas||[]).find(r=>yes(r.Activo)&&['Landing','Inicio'].includes(clean(r['Página']))&&clean(r['Sección']).toLowerCase()===section.toLowerCase()&&clean(r.Campo).toLowerCase()===field.toLowerCase());return row?clean(row.Texto):'';}
  function waHref(number,message){return `https://wa.me/${clean(number).replace(/\D/g,'')||'573202417339'}?text=${encodeURIComponent(clean(message))}`;}
  function wireWhatsApp(cfg){document.querySelectorAll('.wa-link').forEach(a=>{a.href=waHref(cfg.whatsapp,a.dataset.message||cfg.mensaje_general_whatsapp||'Hola Genes Creativos, quiero cotizar un proyecto.');});}
  function setBrand(cfg){const root=document.documentElement;if(cfg.color_principal)root.style.setProperty('--lime',clean(cfg.color_principal));if(cfg.color_secundario)root.style.setProperty('--cyan',clean(cfg.color_secundario));if(cfg.color_terciario)root.style.setProperty('--violet',clean(cfg.color_terciario));if(cfg.color_acento)root.style.setProperty('--pink',clean(cfg.color_acento));const logo=driveImage(cfg.logo_url);if(logo)document.querySelectorAll('.brand-logo').forEach(img=>{img.src=logo;img.alt=clean(cfg.logo_alt)||'Genes Creativos';});if(cfg.titulo_web)document.title=clean(cfg.titulo_web);const meta=document.querySelector('meta[name="description"]');if(meta&&cfg.descripcion_web)meta.content=clean(cfg.descripcion_web);if(valid(cfg.favicon_url||cfg.logo_url)){let f=document.querySelector('link[rel="icon"]');if(!f){f=document.createElement('link');f.rel='icon';document.head.appendChild(f);}f.href=driveImage(cfg.favicon_url||cfg.logo_url);}const counters=document.querySelectorAll('[data-counter]');if(cfg.clientes_satisfechos)counters[0].dataset.counter=clean(cfg.clientes_satisfechos);if(cfg.ciudades_cubiertas)counters[1].dataset.counter=clean(cfg.ciudades_cubiertas);wireWhatsApp(cfg);}
  function setMenu(){const rows=(state.Menu||[]).filter(r=>yes(r.Activo)).sort((a,b)=>Number(a.Orden)-Number(b.Orden));if(!rows.length)return;document.querySelector('.main-nav').innerHTML=rows.filter(r=>clean(r.Destino).startsWith('#')&&clean(r.Destino)!=='#contacto').map(r=>`<a href="${esc(r.Destino)}">${esc(r.Etiqueta)}</a>`).join('');}
  function setBanner(){const row=(state.Banners||[]).filter(r=>yes(r.Activo)&&['Landing','Inicio'].includes(clean(r['Página']))).sort((a,b)=>Number(a.Orden)-Number(b.Orden))[0];if(!row)return;if(row['Título']){const words=clean(row['Título']).replace(/\.$/,'').split(/\s+/);const chunks=[words.slice(0,2).join(' '),words.slice(2,4).join(' '),words.slice(4).join(' ')].filter(Boolean);document.querySelector('#hero-title').innerHTML=chunks.map((x,i)=>i===1?`<span>${esc(x)}.</span>`:`${esc(x)}.`).join('<br>');}if(row['Subtítulo'])document.querySelector('.hero-lead').textContent=clean(row['Subtítulo']);const btn=document.querySelector('.hero-actions .button-primary');if(row['Texto botón'])btn.childNodes[0].nodeValue=clean(row['Texto botón'])+' ';const image=driveImage(row['Imagen URL']);if(image)document.querySelector('.hero-media').style.backgroundImage=`linear-gradient(90deg,rgba(7,7,10,.97) 10%,rgba(7,7,10,.3)),url("${image.replace(/"/g,'%22')}")`;}
  function setTexts(){const map=[['Servicios','titulo','#services-title'],['Servicios','descripcion','.services .section-heading p'],['Moda','titulo','#fashion-title'],['Moda','descripcion','.fashion-intro p'],['Quiénes somos','titulo','#about-title'],['Quiénes somos','descripcion','.about-copy>p'],['Misión','texto','#mission-text'],['Visión','texto','#vision-text'],['Cobertura','titulo','#coverage-title'],['Cobertura','descripcion','#coverage-description'],['Testimonios','titulo','#testimonials-title'],['CTA final','titulo','#final-title'],['CTA final','descripcion','#final-description']];map.forEach(([s,f,q])=>{const v=pageText(s,f),el=document.querySelector(q);if(!v||!el)return;if(f==='titulo'){const words=v.replace(/\.$/,'').split(/\s+/);const cut=Math.max(1,Math.ceil(words.length*.55));el.innerHTML=`${esc(words.slice(0,cut).join(' '))}<br><em>${esc(words.slice(cut).join(' '))}.</em>`;}else el.textContent=v;});}
  function renderServices(cfg){const rows=(state.Servicios||[]).filter(r=>yes(r.Activo)).sort((a,b)=>Number(a.Orden)-Number(b.Orden));if(!rows.length)return;const icons=['▶','✦','⌁','◇','♢','▣'];document.querySelector('#service-grid').innerHTML=rows.map((r,i)=>`<article class="service-card reveal" id="${esc(clean(r['Sección destino']||r['Página destino']).replace(/^.*#/,'')||'servicio-'+i)}"><span class="service-no">${String(i+1).padStart(2,'0')}</span><div class="service-icon">${icons[i%icons.length]}</div><h3>${esc(r.Servicio)}</h3><p>${esc(r.Descripción)}</p><a class="service-cta" href="${waHref(cfg.whatsapp,r['Mensaje WhatsApp'])}" target="_blank" rel="noopener">${esc(r['Texto botón']||'Cotizar')} ↗</a></article>`).join('');observeReveals();}
  function productImage(r,i){const img=driveImage(r['Imagen URL']);if(img)return img;return i===1?'hoodie-black.png':'';}
  function renderProducts(cfg){let rows=(state.Productos||[]).filter(r=>yes(r.Activo)).sort((a,b)=>Number(a.Orden)-Number(b.Orden));if(!rows.length)rows=FALLBACK_PRODUCTS;document.querySelector('#product-grid').innerHTML=rows.map((r,i)=>{const sizes=split(r['Tallas (separadas por |)']),mats=split(r['Materiales (separados por |)']),colors=split(r['Colores (separados por |)']),custom=split(r.Personalización),img=productImage(r,i);return `<article class="product-card reveal" data-name="${esc(r.Nombre)}" data-message="${esc(r['Mensaje WhatsApp'])}"><div class="product-visual">${img?`<img src="${esc(img)}" alt="${esc(r.Nombre)}" loading="lazy">`:`<span class="product-fallback">${['T','H','J','G'][i%4]}</span>`}</div><div class="product-info"><span>${esc(r.Categoría)}</span><h3>${esc(r.Nombre)}</h3><p>${esc(r['Descripción corta'])}</p><div class="chips">${custom.slice(0,4).map(v=>`<span>${esc(v)}</span>`).join('')}</div><div class="product-form"><label>Talla<select class="size">${sizes.map(v=>`<option>${esc(v)}</option>`).join('')}</select></label><label>Cantidad<input class="qty" type="number" min="${Number(r['Cantidad mínima'])||1}" value="${Number(r['Cantidad mínima'])||1}"></label><label>Material<select class="material">${mats.map(v=>`<option>${esc(v)}</option>`).join('')}</select></label><label>Color<select class="color">${colors.map(v=>`<option>${esc(v)}</option>`).join('')}</select></label><button class="product-order" type="button">Enviar pedido a WhatsApp ↗</button></div></div></article>`;}).join('');document.querySelectorAll('.product-order').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.product-card');const msg=`${card.dataset.message||'Hola Genes Creativos, quiero cotizar una prenda.'}\n\nPrenda: ${card.dataset.name}\nTalla: ${card.querySelector('.size').value}\nMaterial: ${card.querySelector('.material').value}\nColor: ${card.querySelector('.color').value}\nCantidad: ${card.querySelector('.qty').value}\n\n¿Me confirman precio y tiempo de entrega?`;window.open(waHref(cfg.whatsapp,msg),'_blank','noopener');}));observeReveals();}
  function renderTestimonials(){const rows=(state.Testimonios||[]).filter(r=>yes(r.Activo));if(!rows.length)return;document.querySelector('#testimonial-track').innerHTML=rows.map(r=>`<article class="testimonial reveal"><div class="stars">${'★'.repeat(Math.max(1,Math.min(5,Number(r['Calificación 1-5'])||5)))}</div><p>“${esc(r.Testimonio)}”</p><strong>${esc(r.Nombre)}</strong><small>${esc([r['Empresa o rol'],r.Ciudad].filter(Boolean).join(' · '))}</small></article>`).join('');observeReveals();}
  let planeTimer;
  function renderCoverage(){let rows=(state.Cobertura||[]).filter(r=>yes(r.Activo)&&Number(r['Posición X'])>=0).sort((a,b)=>Number(a['Orden ruta'])-Number(b['Orden ruta']));if(rows.length<20)rows=FALLBACK_COORDS.map((r,i)=>({Ciudad:r[0],'Posición X':r[1],'Posición Y':r[2],'Orden ruta':i+1,Activo:'Sí'}));const root=document.querySelector('#map-points');root.innerHTML=rows.map((r,i)=>`<span class="map-point" style="left:${Number(r['Posición X'])}%;top:${Number(r['Posición Y'])}%;animation-delay:${(i%8)*.18}s"><label>${esc(r.Ciudad||r.Departamento)}</label></span>`).join('');const plane=document.querySelector('#route-plane'),label=document.querySelector('#route-label');let index=0;clearInterval(planeTimer);function fly(){const r=rows[index%rows.length];plane.style.left=`${Number(r['Posición X'])}%`;plane.style.top=`${Number(r['Posición Y'])}%`;label.textContent=`Ruta activa · ${clean(r.Ciudad||r.Departamento)}`;index++;}fly();planeTimer=setInterval(fly,850);}
  function renderSocial(cfg){const rows=(state.Redes_y_contacto||[]).filter(r=>yes(r.Activo));const social=rows.filter(r=>!['WhatsApp','Correo','Dirección'].includes(clean(r.Tipo))&&valid(r['URL o dato']));if(social.length)document.querySelector('#social-links').innerHTML=social.map(r=>`<a href="${esc(r['URL o dato'])}" target="_blank" rel="noopener">${esc(r['Nombre visible']||r.Tipo)}</a>`).join('');const email=rows.find(r=>clean(r.Tipo)==='Correo')?.['URL o dato']||cfg.correo_principal;if(email){document.querySelectorAll('a[href^="mailto:"]').forEach(a=>{a.href=`mailto:${email}`;if(a.classList.contains('email-link'))a.textContent=email;});}}
  let revealObserver;
  function observeReveals(){if(!revealObserver)revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');revealObserver.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.reveal:not(.in)').forEach(el=>revealObserver.observe(el));}
  function counters(){const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=Number(String(el.dataset.counter).replace(/[^0-9.]/g,''))||0,start=performance.now(),duration=1500;function tick(now){const p=Math.min(1,(now-start)/duration),ease=1-Math.pow(1-p,3);el.textContent=Math.round(target*ease).toLocaleString('es-CO')+(el.dataset.suffix||'');if(p<1)requestAnimationFrame(tick);}requestAnimationFrame(tick);obs.unobserve(el);}),{threshold:.5});document.querySelectorAll('[data-counter]').forEach(el=>obs.observe(el));}
  function interactions(){const header=document.querySelector('.site-header'),toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open);});document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(a)nav.classList.remove('open');});const sections=[...document.querySelectorAll('main section[id],header[id]')];const navLinks=[...document.querySelectorAll('.main-nav a')];const activeObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${e.target.id}`));}),{rootMargin:'-45% 0px -48%'});sections.forEach(s=>activeObs.observe(s));window.addEventListener('scroll',()=>{header.style.boxShadow=scrollY>20?'0 12px 40px rgba(0,0,0,.28)':'none';document.querySelectorAll('.parallax').forEach(el=>{const rect=el.getBoundingClientRect(),speed=Number(el.dataset.speed)||.08;el.style.transform=`translate3d(0,${(rect.top-innerHeight/2)*speed}px,0)`;});},{passive:true});const cursor=document.querySelector('.cursor-pen');document.addEventListener('mousemove',e=>{cursor.style.left=`${e.clientX}px`;cursor.style.top=`${e.clientY}px`;});document.addEventListener('mouseleave',()=>cursor.style.opacity=0);document.addEventListener('mouseenter',()=>cursor.style.opacity=1);document.querySelector('#year').textContent=new Date().getFullYear();}
  async function init(){interactions();observeReveals();const results=await Promise.allSettled(TABS.map(loadTab));results.forEach((result,i)=>{if(result.status==='fulfilled')state[TABS[i]]=result.value;});const cfg=config();setBrand(cfg);setMenu();setBanner();setTexts();renderServices(cfg);renderProducts(cfg);renderTestimonials();renderCoverage();renderSocial(cfg);counters();wireWhatsApp(cfg);document.documentElement.dataset.sheet=results.some(r=>r.status==='fulfilled')?'connected':'fallback';}
  init();
})();
